description: "Updated UnDraw library. These illustrations are designed by Katerina Limpitsouni."
name: "undraw_illustrations"
repository: "https://github.com/RaghavTheGreat1/undraw_illustrations.git"
version: "3.1.0+3"
dependencies:
  flutter_svg: ^2.0.3
  http:
  flutter:
    sdk: "flutter"
dev_dependencies:
  cli_util: "^0.3.0"
  yaml: ^3.1.1
  fhir_yaml: ^0.9.0
  flutter_test:
    sdk: "flutter"
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter: null
